spring.datasource.url=jdbc:mysql://localhost:3306/nidan_vitals_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=aisha@23

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db.sql

server.port=8080
